# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YQs4WvFOqJ+vIDaralqoAiKV5rSDQARHxDCh+KjsAs2KjuvvZ1R3fE9XCwUfh9cwtZLytMTbXv13MTMT0FiY1mVttRF6xtX9fPOZjJvXOqa71tnR4QWo+yeaXc8N1hIV8xcMHXbrNht2HiThY2NDqTnCxPm9AhHTswllnIK1rd9fJZ/thDIUZa0+TC1extbtgzcEcOVtKCyE8m08g+kIPs83MTO8n3YmhCyjRo9qg9qEzWtQbGxMr5HHNwfK8ibR22QaUosP+lBL/yQ02SyZJyDN7QlAThqIXwtw1DIVZYrryHc8uj7e3uyuwVusBesgCXPuzC5tmsq+cg0tyUBsTHUHUF0TMhIrAKFI41UIVyrXKrq+izHR8DYl+oPnjHf5DmgOO0giIY0kBeXQBEh2zK63Fd43k8lyy34HiqdjWcS2IRbNNgLY5YxPdJaWPiISrzyPdRe9LjfcyUVuJA/d34OhHpfjnOjPW7+qNXvOwM5ktlYbY96Kmi2IlQ1q6lqJwooelUG06enslCFmjJ2w1vnpZR/JtX8/d6uyTOa6A5BWUJF5PdQrODhKLj9g6cV2ekSOcZETaUNieusCCycEnQsYuzREuxwdVnlqCuh01+GlghmkRBSu4u0+BYONh6uqPBgtDTd0gV1ppVmwgHxevJN4qCQUfU3c0bNmemyULMQ=
    # SESSION
    - secure: lskLjft/6z4y999Vc9JfANJEhmn+GqwZ3ch1nBpqUqqj6yR0jDkq4dt65cPpIQu6dQKbZP07A2BbC8cRwzXuhRLfOTh49VlPT2/9LKA/XOxP/lgeFgb9QzGLZK08q5pe9hWRnMF37+0nvhiwFot2F3ytfTtJs2YBDWUfyCOh3q4OqHjBlOQ2g50ITw3BYPh/NPXCGgMkibgh1e6fSvGE58Qr3UHJjDcpfqxkvRxf233ULdARAlxtSc3Gj0eCeyAHfSKUsCzJCAsSrrFfFv8tejJal1gXVjRiC/b3QLL5WS3RkoHva8RHEZE9vjBqOXmjKNl9BPXulfjxjxecHkyRTn9AMIgB2Anee1fF5YFNA+YFXwmw6jcOpMauQLZ7+Emv2ZoZ2LLrPjY2kRINLqb/v+DLb0yl/GGpZeOCg69WrQCHSeFYNfoD+4V3PiSU889F30gxQTWphK0l+rKlSuQcFlRWvnuFX/7THmXk00SGYgmu1b3eRbpQIiNlSMWPccTuK63P/9qFvGD998QQ1ssm+VXKwwgUzOduhs0hM2SVffxii1BS1gL6VONmMgsF6yF01bbbIwRO//4BJ7HkFkYiq2sOdQrK6hehteXIjGp5oYLvWu+5pNlrRSl5ZNK5VgannWlmYf85jdZCUun2Ur7e9OEomEUiGSuiI89S+P1AwZQ=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: nDBH8e4CrokG6Ir8Md0FPN2UWxVDYT7YeizeQz3BJDBmDLtpBZjqo2w5nuZ5PV6ZthjZz8gpDC6IedHVwkv58fANdpEYAjWd/l+dwf18QdrLuPppNuWYURAxxYbExwpoDowU6yHytBSLcEqGfLJkGo5Q7iKVa9lySK8PBWGBNwYT23CpIXNjQ0v8EnMY0bP9IgAAqvKYOFseZZeUjaNbaIa93UdeVeJwkYl1iCVYwglZUynjne5nzSleIczgAJb4yDVqnIUfUvucZ/IgQ+YKoUjVK4EemC+gDFSHzuQXzYsD7IJKOYO2igmOzEi5DBPmqvkn+dN/2QlUo+yaEnF8WFYQcOmCjb/gMZsbvym9RUxt1jEP2HBaTBL1yqqZZQvVfnR1XQt1jH8SmH6PbgTGeTHUFHslBXsO/es5CvwYeLOUAw8AMdvU9z7tvHRhFc13Puljulz2mTIivgP2ktNwb7JjYW1sH8kjoQQVL3Yxz+xtOjrhp9u5n85Mj2SCUZkrZnFG5UVFtTK3XuFTSQxNznsDl38e2o1UdZgHyWhyhJgYNH7pNrHWcS5QkAEooXM57LnzsS53SaKGzdQaoplTJuNyDU2U/AOkO7FZZRpFTozH8H8BDgvk15m0OI/Gu03B+KB4TfPi6Jm7Jfe+gI8Ej8Kv5dGNyTDe6+eifle4Xs0=
