# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YQs4WvFOqJ+vIDaralqoAiKV5rSDQARHxDCh+KjsAs2KjuvvZ1R3fE9XCwUfh9cwtZLytMTbXv13MTMT0FiY1mVttRF6xtX9fPOZjJvXOqa71tnR4QWo+yeaXc8N1hIV8xcMHXbrNht2HiThY2NDqTnCxPm9AhHTswllnIK1rd9fJZ/thDIUZa0+TC1extbtgzcEcOVtKCyE8m08g+kIPs83MTO8n3YmhCyjRo9qg9qEzWtQbGxMr5HHNwfK8ibR22QaUosP+lBL/yQ02SyZJyDN7QlAThqIXwtw1DIVZYrryHc8uj7e3uyuwVusBesgCXPuzC5tmsq+cg0tyUBsTHUHUF0TMhIrAKFI41UIVyrXKrq+izHR8DYl+oPnjHf5DmgOO0giIY0kBeXQBEh2zK63Fd43k8lyy34HiqdjWcS2IRbNNgLY5YxPdJaWPiISrzyPdRe9LjfcyUVuJA/d34OhHpfjnOjPW7+qNXvOwM5ktlYbY96Kmi2IlQ1q6lqJwooelUG06enslCFmjJ2w1vnpZR/JtX8/d6uyTOa6A5BWUJF5PdQrODhKLj9g6cV2ekSOcZETaUNieusCCycEnQsYuzREuxwdVnlqCuh01+GlghmkRBSu4u0+BYONh6uqPBgtDTd0gV1ppVmwgHxevJN4qCQUfU3c0bNmemyULMQ=
    # SESSION
    - secure: Jahy9iPwuJMg6ZRtwcdENA1VTPZ/gPw3e9O2yuilzSO2Yz4D2pPBFYmOlt1F/CTO/9CpgVJ14qFB0hgj4MNdHOM4K24juLOiJcSDNkPnX8DqKRGJvK6nuIHoGjoLSmPEi/sgDcDc4C9U7NFor1JcOH3NPTW7xBsruybMXUjp9ylTw2ukoekXTmA6BYmJT2KoHv6RZPSj0nSXxUO/Wv19fLPZwPzRZbc+D2AZx6uInG+u+wNL78zvS0Ao2oKa7aNakm9W5b56MvWKmleG8hshSjcqZBmgkm6dRTkqHXcko790/4MGEbPza6r8K7qUG5ZhOsF2erAeDLgE/PmerwNk5QN1iWKVlcqkDB1yF0S1nW9+k6/45QyOolVW8rCphz2WLZHQK/NDrX88WGrL+AuABNagKkYgJat2nmPp2GC1zCDgJ4aOEBCdlvYiNG9zP/e+IVnTTzzNYJNMOXZd8ylto48sE2qpnoW+eU+I4l1jX2EBR9jR0zANZ4b8QIZut39i1G6UyKzrO7N2PC1H7OS8zKGeM/YIJhTD1UTrPAxoH0VQC7gW2hsPqipU/SOjl1RYUXkKaErcKkIeZmwkpOeuCIxIi7iXJSAM2tEx118F6z9Wm1Uug8Gfz45M10aGHWiQ+BdDkfcBb/D75wmJ0aNRACpThWhtrVbI7t+hnNQXjMM=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: nDBH8e4CrokG6Ir8Md0FPN2UWxVDYT7YeizeQz3BJDBmDLtpBZjqo2w5nuZ5PV6ZthjZz8gpDC6IedHVwkv58fANdpEYAjWd/l+dwf18QdrLuPppNuWYURAxxYbExwpoDowU6yHytBSLcEqGfLJkGo5Q7iKVa9lySK8PBWGBNwYT23CpIXNjQ0v8EnMY0bP9IgAAqvKYOFseZZeUjaNbaIa93UdeVeJwkYl1iCVYwglZUynjne5nzSleIczgAJb4yDVqnIUfUvucZ/IgQ+YKoUjVK4EemC+gDFSHzuQXzYsD7IJKOYO2igmOzEi5DBPmqvkn+dN/2QlUo+yaEnF8WFYQcOmCjb/gMZsbvym9RUxt1jEP2HBaTBL1yqqZZQvVfnR1XQt1jH8SmH6PbgTGeTHUFHslBXsO/es5CvwYeLOUAw8AMdvU9z7tvHRhFc13Puljulz2mTIivgP2ktNwb7JjYW1sH8kjoQQVL3Yxz+xtOjrhp9u5n85Mj2SCUZkrZnFG5UVFtTK3XuFTSQxNznsDl38e2o1UdZgHyWhyhJgYNH7pNrHWcS5QkAEooXM57LnzsS53SaKGzdQaoplTJuNyDU2U/AOkO7FZZRpFTozH8H8BDgvk15m0OI/Gu03B+KB4TfPi6Jm7Jfe+gI8Ej8Kv5dGNyTDe6+eifle4Xs0=
