# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YQs4WvFOqJ+vIDaralqoAiKV5rSDQARHxDCh+KjsAs2KjuvvZ1R3fE9XCwUfh9cwtZLytMTbXv13MTMT0FiY1mVttRF6xtX9fPOZjJvXOqa71tnR4QWo+yeaXc8N1hIV8xcMHXbrNht2HiThY2NDqTnCxPm9AhHTswllnIK1rd9fJZ/thDIUZa0+TC1extbtgzcEcOVtKCyE8m08g+kIPs83MTO8n3YmhCyjRo9qg9qEzWtQbGxMr5HHNwfK8ibR22QaUosP+lBL/yQ02SyZJyDN7QlAThqIXwtw1DIVZYrryHc8uj7e3uyuwVusBesgCXPuzC5tmsq+cg0tyUBsTHUHUF0TMhIrAKFI41UIVyrXKrq+izHR8DYl+oPnjHf5DmgOO0giIY0kBeXQBEh2zK63Fd43k8lyy34HiqdjWcS2IRbNNgLY5YxPdJaWPiISrzyPdRe9LjfcyUVuJA/d34OhHpfjnOjPW7+qNXvOwM5ktlYbY96Kmi2IlQ1q6lqJwooelUG06enslCFmjJ2w1vnpZR/JtX8/d6uyTOa6A5BWUJF5PdQrODhKLj9g6cV2ekSOcZETaUNieusCCycEnQsYuzREuxwdVnlqCuh01+GlghmkRBSu4u0+BYONh6uqPBgtDTd0gV1ppVmwgHxevJN4qCQUfU3c0bNmemyULMQ=
    # SESSION
    - secure: XkVBKHEym6r3TZDBBmEEej3hk2K8RjFc1S+GT7TpLfWUP0FVH6oarE1MEe/yuHhf+BYZeBLWSpGnZk8X3LpwXNta36+9SAjRNyOiUXJ3S1LFSfj76zpP0WOPuixAPLAXyvXNEhRfV0bk52zkAE5lKFCEeI4n/WewEf0mO88Zr9+JF5eqHZeMAYE15tM96FKnuigkk1rIzvKCzhBFfbADohYZNj4jrGaGwAdQCc/Cc1G8tCxMKv9oNFeJmK2PHGHWVq5YPGQlncDgO369gfD43XsO6osPYDFbqoEKTxA4TRFyl/cns3pLYIG+2d5bMTPR2ZFCWLD6KUfyUFgkJKQRl8ENIIWm9iNz/cncUd91WtvjR4pNw4AynOkxZ31ffZFRMO3J7aKaemv1dZzWTVupDmN4eSXeVrPxJ9bj+0Pbo5up0Fk4qLsvo4Gwe2koAgMEpLNqaZStU+V5RGSlBwbnVOE5CnDIPxfNCY0oG0pwZRcQGzYbCH78DZ1bVYu/ma1F91DghYwBNDkX5L638h3IXsApBNyB8SFi5yK3Gr+OOKE7TkBagl9P5Uro+wPmf1EegNg48/+Hmm0d3cL3dccyaiZwIx8aVpGQg4tR7H40lCZunfo6KC52vlqEIe2ydSm1ehNZRofES7lfNYTQ6at1BQY4POCRP+eyT37FSimn68Y=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: nDBH8e4CrokG6Ir8Md0FPN2UWxVDYT7YeizeQz3BJDBmDLtpBZjqo2w5nuZ5PV6ZthjZz8gpDC6IedHVwkv58fANdpEYAjWd/l+dwf18QdrLuPppNuWYURAxxYbExwpoDowU6yHytBSLcEqGfLJkGo5Q7iKVa9lySK8PBWGBNwYT23CpIXNjQ0v8EnMY0bP9IgAAqvKYOFseZZeUjaNbaIa93UdeVeJwkYl1iCVYwglZUynjne5nzSleIczgAJb4yDVqnIUfUvucZ/IgQ+YKoUjVK4EemC+gDFSHzuQXzYsD7IJKOYO2igmOzEi5DBPmqvkn+dN/2QlUo+yaEnF8WFYQcOmCjb/gMZsbvym9RUxt1jEP2HBaTBL1yqqZZQvVfnR1XQt1jH8SmH6PbgTGeTHUFHslBXsO/es5CvwYeLOUAw8AMdvU9z7tvHRhFc13Puljulz2mTIivgP2ktNwb7JjYW1sH8kjoQQVL3Yxz+xtOjrhp9u5n85Mj2SCUZkrZnFG5UVFtTK3XuFTSQxNznsDl38e2o1UdZgHyWhyhJgYNH7pNrHWcS5QkAEooXM57LnzsS53SaKGzdQaoplTJuNyDU2U/AOkO7FZZRpFTozH8H8BDgvk15m0OI/Gu03B+KB4TfPi6Jm7Jfe+gI8Ej8Kv5dGNyTDe6+eifle4Xs0=
