# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - 4

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YQs4WvFOqJ+vIDaralqoAiKV5rSDQARHxDCh+KjsAs2KjuvvZ1R3fE9XCwUfh9cwtZLytMTbXv13MTMT0FiY1mVttRF6xtX9fPOZjJvXOqa71tnR4QWo+yeaXc8N1hIV8xcMHXbrNht2HiThY2NDqTnCxPm9AhHTswllnIK1rd9fJZ/thDIUZa0+TC1extbtgzcEcOVtKCyE8m08g+kIPs83MTO8n3YmhCyjRo9qg9qEzWtQbGxMr5HHNwfK8ibR22QaUosP+lBL/yQ02SyZJyDN7QlAThqIXwtw1DIVZYrryHc8uj7e3uyuwVusBesgCXPuzC5tmsq+cg0tyUBsTHUHUF0TMhIrAKFI41UIVyrXKrq+izHR8DYl+oPnjHf5DmgOO0giIY0kBeXQBEh2zK63Fd43k8lyy34HiqdjWcS2IRbNNgLY5YxPdJaWPiISrzyPdRe9LjfcyUVuJA/d34OhHpfjnOjPW7+qNXvOwM5ktlYbY96Kmi2IlQ1q6lqJwooelUG06enslCFmjJ2w1vnpZR/JtX8/d6uyTOa6A5BWUJF5PdQrODhKLj9g6cV2ekSOcZETaUNieusCCycEnQsYuzREuxwdVnlqCuh01+GlghmkRBSu4u0+BYONh6uqPBgtDTd0gV1ppVmwgHxevJN4qCQUfU3c0bNmemyULMQ=
    # SESSION
    - secure: RcdWOwNSNAgP0iIumDo+1ATbVymEY1jzH/PPk76vyksy6ncA72K1qYJsRa1wydncpmyrvdA/2TkoByP/sFov3DmY4fqhnmrwXMYWP5SyYwDRGGKMhoH0wzoL/xE58VzuVjSkT3jD3DQ47MUIayKSupAYzOLoclZBcxq2j4RhSj6P6NpiDNcmCtaS4gXm0NiZ9OGkAqLL8H3kVUne3hVYlxRst1158HiuqLgeC7qKT6NShu7xPxQ5MEizeV0oP1YVtM5DrxUy7lbWf9yUu1dSNdj+Hyrh0+mkdyHLEyWWnMLDR/OQNkSlXkGBS2aAcrcnGd760GRKLbwSZKveYUMvbBDyY7SyY1GoSohdZpzQXv7Kd90Zh1yY1Yfsld1KEQbE4oLK1FzU5TW0esoGO0U+cVqPZ/GJqHCVsUjd06DK1+Jl3Axd0/kCxRmsK+wboisruuCUbQf1nGZQI+e8zL61sAemM9oyt4X3kHrXBB0iWynzI9mv5i1xM4gqaU8EgbLMOfXaECwINkA5b3gPVDBIHg6gGS18s5nFzste1tPBLpLyA+96jIn4WasUNFw4le9J9cwfs4h3LSAB+K8iGSSabpfUKtJ5EnNs0FIeWgdFF+qJh4W2yOCfVVv5hER3wRiVpFYpUaRSonsGg8GFj+5frS+DujuX5dSusEuR89kZ/Y8=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: nDBH8e4CrokG6Ir8Md0FPN2UWxVDYT7YeizeQz3BJDBmDLtpBZjqo2w5nuZ5PV6ZthjZz8gpDC6IedHVwkv58fANdpEYAjWd/l+dwf18QdrLuPppNuWYURAxxYbExwpoDowU6yHytBSLcEqGfLJkGo5Q7iKVa9lySK8PBWGBNwYT23CpIXNjQ0v8EnMY0bP9IgAAqvKYOFseZZeUjaNbaIa93UdeVeJwkYl1iCVYwglZUynjne5nzSleIczgAJb4yDVqnIUfUvucZ/IgQ+YKoUjVK4EemC+gDFSHzuQXzYsD7IJKOYO2igmOzEi5DBPmqvkn+dN/2QlUo+yaEnF8WFYQcOmCjb/gMZsbvym9RUxt1jEP2HBaTBL1yqqZZQvVfnR1XQt1jH8SmH6PbgTGeTHUFHslBXsO/es5CvwYeLOUAw8AMdvU9z7tvHRhFc13Puljulz2mTIivgP2ktNwb7JjYW1sH8kjoQQVL3Yxz+xtOjrhp9u5n85Mj2SCUZkrZnFG5UVFtTK3XuFTSQxNznsDl38e2o1UdZgHyWhyhJgYNH7pNrHWcS5QkAEooXM57LnzsS53SaKGzdQaoplTJuNyDU2U/AOkO7FZZRpFTozH8H8BDgvk15m0OI/Gu03B+KB4TfPi6Jm7Jfe+gI8Ej8Kv5dGNyTDe6+eifle4Xs0=
