# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: YQs4WvFOqJ+vIDaralqoAiKV5rSDQARHxDCh+KjsAs2KjuvvZ1R3fE9XCwUfh9cwtZLytMTbXv13MTMT0FiY1mVttRF6xtX9fPOZjJvXOqa71tnR4QWo+yeaXc8N1hIV8xcMHXbrNht2HiThY2NDqTnCxPm9AhHTswllnIK1rd9fJZ/thDIUZa0+TC1extbtgzcEcOVtKCyE8m08g+kIPs83MTO8n3YmhCyjRo9qg9qEzWtQbGxMr5HHNwfK8ibR22QaUosP+lBL/yQ02SyZJyDN7QlAThqIXwtw1DIVZYrryHc8uj7e3uyuwVusBesgCXPuzC5tmsq+cg0tyUBsTHUHUF0TMhIrAKFI41UIVyrXKrq+izHR8DYl+oPnjHf5DmgOO0giIY0kBeXQBEh2zK63Fd43k8lyy34HiqdjWcS2IRbNNgLY5YxPdJaWPiISrzyPdRe9LjfcyUVuJA/d34OhHpfjnOjPW7+qNXvOwM5ktlYbY96Kmi2IlQ1q6lqJwooelUG06enslCFmjJ2w1vnpZR/JtX8/d6uyTOa6A5BWUJF5PdQrODhKLj9g6cV2ekSOcZETaUNieusCCycEnQsYuzREuxwdVnlqCuh01+GlghmkRBSu4u0+BYONh6uqPBgtDTd0gV1ppVmwgHxevJN4qCQUfU3c0bNmemyULMQ=
    # SESSION
    - secure: t/spq4tzS+YwONNEySkVZVtvh/KVu9uXWhUV/6tm/HJVGshGB1v6BTAfH/8AxRxw0+Kq99iT46dvc9TcQY2f2lUjDetN3IcPJ8+WPVOZGujGTIBQZZhvcg+5a7VhVw9ISUAD4tADkbk2tgI4Q+6fteo/mE2HDltj8uCAoijh5PQaR7oblhC+CdaIbYFuFdhSv4Yikt405DxdzL6CdUbrltgzYO5SGzbC+QwsvUdFVKYjmWg+FdLkjjBtljqcOJsnE72MKwOVprO2FTDDKKu+omF0xnA8LykkI4AIxoiPLIS3LYqjSiNv+/X2zJgZGVVVJ620h+c+bomiHK7GjPZGQFPOlOZMETNgIt1VuCqH06L8bK0XtW7VO1HlRIXyq8sG+XSdawFzOXh8E6RPpZBS6mrf/vX3c28ZeCdyoSDqW67rYlHtZqlXIFqqNwXnSPu9+DJ1CP6cYT8DsslflTgKkXp3wO11H39EvAx3BCx896s377e0DfOFSp1ifRRsoG371D/dNU3uj6ybRscMYy07OFwADiqW53LvbHC9eht0LMpIXSzkAYNmmHj/GY23eUFiJ+1+26w4K3Z2qEvoejd3O0hTreGm51KvHD76NGM2ys9QRLaZ66vh5AOAi0QFiDefMPkqE70iN15Qj8DLNwA17CCNaT2umjdzo2ZU2228Gb8=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: nDBH8e4CrokG6Ir8Md0FPN2UWxVDYT7YeizeQz3BJDBmDLtpBZjqo2w5nuZ5PV6ZthjZz8gpDC6IedHVwkv58fANdpEYAjWd/l+dwf18QdrLuPppNuWYURAxxYbExwpoDowU6yHytBSLcEqGfLJkGo5Q7iKVa9lySK8PBWGBNwYT23CpIXNjQ0v8EnMY0bP9IgAAqvKYOFseZZeUjaNbaIa93UdeVeJwkYl1iCVYwglZUynjne5nzSleIczgAJb4yDVqnIUfUvucZ/IgQ+YKoUjVK4EemC+gDFSHzuQXzYsD7IJKOYO2igmOzEi5DBPmqvkn+dN/2QlUo+yaEnF8WFYQcOmCjb/gMZsbvym9RUxt1jEP2HBaTBL1yqqZZQvVfnR1XQt1jH8SmH6PbgTGeTHUFHslBXsO/es5CvwYeLOUAw8AMdvU9z7tvHRhFc13Puljulz2mTIivgP2ktNwb7JjYW1sH8kjoQQVL3Yxz+xtOjrhp9u5n85Mj2SCUZkrZnFG5UVFtTK3XuFTSQxNznsDl38e2o1UdZgHyWhyhJgYNH7pNrHWcS5QkAEooXM57LnzsS53SaKGzdQaoplTJuNyDU2U/AOkO7FZZRpFTozH8H8BDgvk15m0OI/Gu03B+KB4TfPi6Jm7Jfe+gI8Ej8Kv5dGNyTDe6+eifle4Xs0=
